<?php

namespace UCP\AbsenceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UCP\AbsenceBundle\Entity\Lesson;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
	public function findAbsentByLesson(Lesson $lesson)
	{
		$query = $this->_em->createQuery('SELECT s FROM UCPAbsenceBundle:Student s JOIN s.absences a WHERE a.lesson = ?1')
			->setParameter(1, $lesson);

		return $query->getResult();
	}
}
